2024-07-05 03:19:11,816 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'init' at Fri, 05 Jul 2024 03:19:11 +0000. Up 8.36 seconds.
2024-07-05 03:19:11,816 - main.py[DEBUG]: No kernel command line url found.
2024-07-05 03:19:11,816 - main.py[DEBUG]: Closing stdin.
2024-07-05 03:19:11,817 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=False)
2024-07-05 03:19:11,818 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-07-05 03:19:11,837 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=False)
2024-07-05 03:19:11,838 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-07-05 03:19:11,852 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-instance (recursive=False)
2024-07-05 03:19:11,853 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-07-05 03:19:11,859 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-once (recursive=False)
2024-07-05 03:19:11,860 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-07-05 03:19:11,878 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-boot (recursive=False)
2024-07-05 03:19:11,892 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-07-05 03:19:11,902 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/vendor (recursive=False)
2024-07-05 03:19:11,903 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-07-05 03:19:11,933 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/seed (recursive=False)
2024-07-05 03:19:11,933 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-07-05 03:19:11,962 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances (recursive=False)
2024-07-05 03:19:11,963 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-07-05 03:19:11,993 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/handlers (recursive=False)
2024-07-05 03:19:11,994 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-07-05 03:19:12,026 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/sem (recursive=False)
2024-07-05 03:19:12,027 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data (recursive=False)
2024-07-05 03:19:12,028 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init (recursive=True)
2024-07-05 03:19:12,029 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/sem (recursive=False)
2024-07-05 03:19:12,030 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2024-07-05 03:19:12,042 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2024-07-05 03:19:12,043 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2024-07-05 03:19:12,044 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 0:4
2024-07-05 03:19:12,044 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 3 bytes
2024-07-05 03:19:12,045 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2024-07-05 03:19:12,048 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2024-07-05 03:19:12,048 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2024-07-05 03:19:12,054 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2024-07-05 03:19:12,062 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2024-07-05 03:19:12,078 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2024-07-05 03:19:12,101 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2024-07-05 03:19:12,108 - stages.py[DEBUG]: no cache found
2024-07-05 03:19:12,123 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2024-07-05 03:19:12,123 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2024-07-05 03:19:12,132 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-07-05 03:19:12,132 - __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2024-07-05 03:19:12,148 - __init__.py[DEBUG]: Searching for network data source in: ['DataSourceEc2', 'DataSourceNone']
2024-07-05 03:19:12,148 - handlers.py[DEBUG]: start: init-network/search-Ec2: searching for network data from DataSourceEc2
2024-07-05 03:19:12,148 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
2024-07-05 03:19:12,149 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2024-07-05 03:19:12,149 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2024-07-05 03:19:12,149 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_uuid
2024-07-05 03:19:12,149 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2024-07-05 03:19:12,149 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2024-07-05 03:19:12,149 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2024-07-05 03:19:12,149 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_name=aws cloud_platform=ec2
2024-07-05 03:19:12,150 - util.py[DEBUG]: Skipping DNS checks of IP address 169.254.169.254
2024-07-05 03:19:12,150 - util.py[DEBUG]: Resolving URL: http://169.254.169.254:80 took 0.000 seconds
2024-07-05 03:19:12,150 - util.py[DEBUG]: Skipping DNS checks of IP address fd00:ec2::254
2024-07-05 03:19:12,150 - util.py[DEBUG]: Resolving URL: http://[fd00:ec2::254]:80 took 0.000 seconds
2024-07-05 03:19:12,150 - DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
2024-07-05 03:19:12,151 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/latest/api/token' with {'url': 'http://169.254.169.254:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'timeout': 50.0, 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2024-07-05 03:19:12,163 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/latest/api/token (200, 56b) after 1 attempts
2024-07-05 03:19:12,163 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254:80'
2024-07-05 03:19:12,163 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,172 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2024-07-05 03:19:12,172 - DataSourceEc2.py[DEBUG]: Found preferred metadata version 2021-03-23
2024-07-05 03:19:12,172 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/user-data' with {'url': 'http://169.254.169.254:80/2021-03-23/user-data', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,182 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/user-data (200, 2476b) after 1 attempts
2024-07-05 03:19:12,184 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,192 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ (200, 318b) after 1 attempts
2024-07-05 03:19:12,192 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,204 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
2024-07-05 03:19:12,204 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,208 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami (200, 4b) after 1 attempts
2024-07-05 03:19:12,209 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,222 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
2024-07-05 03:19:12,223 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,225 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/ (200, 12b) after 1 attempts
2024-07-05 03:19:12,225 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,228 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/ (200, 17b) after 1 attempts
2024-07-05 03:19:12,228 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,242 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history (200, 2b) after 1 attempts
2024-07-05 03:19:12,243 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,248 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled (200, 2b) after 1 attempts
2024-07-05 03:19:12,248 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,252 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/ (200, 26b) after 1 attempts
2024-07-05 03:19:12,252 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,263 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/info (200, 216b) after 1 attempts
2024-07-05 03:19:12,263 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,266 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ (200, 4b) after 1 attempts
2024-07-05 03:19:12,266 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,270 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/ (200, 26b) after 1 attempts
2024-07-05 03:19:12,270 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,275 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info (200, 98b) after 1 attempts
2024-07-05 03:19:12,275 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,282 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/ (200, 7b) after 1 attempts
2024-07-05 03:19:12,283 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,291 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
2024-07-05 03:19:12,292 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,302 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/ (200, 11b) after 1 attempts
2024-07-05 03:19:12,303 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,305 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/ (200, 5b) after 1 attempts
2024-07-05 03:19:12,306 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,308 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
2024-07-05 03:19:12,309 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,323 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/ (200, 230b) after 1 attempts
2024-07-05 03:19:12,323 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/ipv4-associations/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/ipv4-associations/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,326 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/ipv4-associations/ (200, 13b) after 1 attempts
2024-07-05 03:19:12,326 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/ipv4-associations/18.236.83.215' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/ipv4-associations/18.236.83.215', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,332 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/ipv4-associations/18.236.83.215 (200, 13b) after 1 attempts
2024-07-05 03:19:12,332 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/device-number' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/device-number', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,337 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/device-number (200, 1b) after 1 attempts
2024-07-05 03:19:12,337 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/interface-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/interface-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,340 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/interface-id (200, 21b) after 1 attempts
2024-07-05 03:19:12,340 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,343 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/local-hostname (200, 43b) after 1 attempts
2024-07-05 03:19:12,343 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/local-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/local-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,352 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/local-ipv4s (200, 13b) after 1 attempts
2024-07-05 03:19:12,352 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,362 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/mac (200, 17b) after 1 attempts
2024-07-05 03:19:12,363 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/owner-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/owner-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,372 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/owner-id (200, 12b) after 1 attempts
2024-07-05 03:19:12,373 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,383 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/public-hostname (200, 49b) after 1 attempts
2024-07-05 03:19:12,384 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/public-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/public-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,387 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/public-ipv4s (200, 13b) after 1 attempts
2024-07-05 03:19:12,387 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/security-group-ids' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/security-group-ids', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,402 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/security-group-ids (200, 20b) after 1 attempts
2024-07-05 03:19:12,402 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,406 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/security-groups (200, 56b) after 1 attempts
2024-07-05 03:19:12,406 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/subnet-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/subnet-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,412 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/subnet-id (200, 24b) after 1 attempts
2024-07-05 03:19:12,413 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/subnet-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,416 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/subnet-ipv4-cidr-block (200, 14b) after 1 attempts
2024-07-05 03:19:12,416 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/vpc-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/vpc-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,422 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/vpc-id (200, 21b) after 1 attempts
2024-07-05 03:19:12,422 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/vpc-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,425 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
2024-07-05 03:19:12,425 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/vpc-ipv4-cidr-blocks', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,432 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/02:91:9a:01:4b:83/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
2024-07-05 03:19:12,433 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,436 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/ (200, 45b) after 1 attempts
2024-07-05 03:19:12,436 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,438 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone (200, 10b) after 1 attempts
2024-07-05 03:19:12,438 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,442 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id (200, 8b) after 1 attempts
2024-07-05 03:19:12,442 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,452 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/region (200, 9b) after 1 attempts
2024-07-05 03:19:12,452 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-keys/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-keys/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,458 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-keys/ (200, 8b) after 1 attempts
2024-07-05 03:19:12,458 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-keys/0/openssh-key' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-keys/0/openssh-key', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,473 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-keys/0/openssh-key (200, 88b) after 1 attempts
2024-07-05 03:19:12,473 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,477 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/ (200, 16b) after 1 attempts
2024-07-05 03:19:12,477 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,483 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/domain (200, 13b) after 1 attempts
2024-07-05 03:19:12,483 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,489 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/partition (200, 3b) after 1 attempts
2024-07-05 03:19:12,489 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,492 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-id (200, 21b) after 1 attempts
2024-07-05 03:19:12,492 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,503 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index (200, 1b) after 1 attempts
2024-07-05 03:19:12,503 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,507 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path (200, 9b) after 1 attempts
2024-07-05 03:19:12,507 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,521 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/hostname (200, 43b) after 1 attempts
2024-07-05 03:19:12,521 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,536 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-action (200, 4b) after 1 attempts
2024-07-05 03:19:12,537 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,540 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2024-07-05 03:19:12,540 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,552 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle (200, 9b) after 1 attempts
2024-07-05 03:19:12,553 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,557 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-type (200, 8b) after 1 attempts
2024-07-05 03:19:12,557 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,561 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-hostname (200, 43b) after 1 attempts
2024-07-05 03:19:12,561 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,572 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4 (200, 13b) after 1 attempts
2024-07-05 03:19:12,572 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,575 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/mac (200, 17b) after 1 attempts
2024-07-05 03:19:12,575 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/profile' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/profile', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,577 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/profile (200, 11b) after 1 attempts
2024-07-05 03:19:12,577 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,581 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-hostname (200, 49b) after 1 attempts
2024-07-05 03:19:12,581 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,583 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4 (200, 13b) after 1 attempts
2024-07-05 03:19:12,584 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,592 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/reservation-id (200, 19b) after 1 attempts
2024-07-05 03:19:12,592 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,595 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/security-groups (200, 56b) after 1 attempts
2024-07-05 03:19:12,597 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,600 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity (200, 32b) after 1 attempts
2024-07-05 03:19:12,601 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,603 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document (200, 477b) after 1 attempts
2024-07-05 03:19:12,604 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,612 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7 (200, 1171b) after 1 attempts
2024-07-05 03:19:12,612 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,615 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048 (200, 1491b) after 1 attempts
2024-07-05 03:19:12,615 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-07-05 03:19:12,618 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature (200, 174b) after 1 attempts
2024-07-05 03:19:12,618 - util.py[DEBUG]: Crawl of metadata service took 0.468 seconds
2024-07-05 03:19:12,622 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-aws - wb: [644] 4 bytes
2024-07-05 03:19:12,623 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2024-07-05 03:19:12,624 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2024-07-05 03:19:12,624 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-aws'
2024-07-05 03:19:12,626 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmpd3cl2nx8) - w: [600] 12265 bytes/chars
2024-07-05 03:19:12,627 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmp9mockaa9) - w: [644] 8123 bytes/chars
2024-07-05 03:19:12,627 - handlers.py[DEBUG]: finish: init-network/search-Ec2: SUCCESS: found network data from DataSourceEc2
2024-07-05 03:19:12,627 - stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
2024-07-05 03:19:12,628 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2024-07-05 03:19:12,628 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2024-07-05 03:19:12,628 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:12,655 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2024-07-05 03:19:12,655 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2024-07-05 03:19:12,655 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:12,656 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2024-07-05 03:19:12,657 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2024-07-05 03:19:12,657 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:12,672 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2024-07-05 03:19:12,672 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2024-07-05 03:19:12,672 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:12,681 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2024-07-05 03:19:12,681 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2024-07-05 03:19:12,681 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:12,684 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2024-07-05 03:19:12,684 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:12,684 - util.py[DEBUG]: loaded blob returned None, returning default.
2024-07-05 03:19:12,685 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2024-07-05 03:19:12,685 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-09542aec432627a9a'
2024-07-05 03:19:12,686 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a (recursive=True)
2024-07-05 03:19:12,693 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/handlers (recursive=False)
2024-07-05 03:19:12,694 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a (recursive=True)
2024-07-05 03:19:12,712 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/scripts (recursive=False)
2024-07-05 03:19:12,713 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a (recursive=True)
2024-07-05 03:19:12,726 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem (recursive=False)
2024-07-05 03:19:12,726 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-09542aec432627a9a/datasource (quiet=False)
2024-07-05 03:19:12,727 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/datasource - wb: [644] 29 bytes
2024-07-05 03:19:12,727 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/datasource (recursive=False)
2024-07-05 03:19:12,729 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/datasource (recursive=False)
2024-07-05 03:19:12,729 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
2024-07-05 03:19:12,730 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2024-07-05 03:19:12,741 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2024-07-05 03:19:12,742 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2024-07-05 03:19:12,742 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2024-07-05 03:19:12,742 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2024-07-05 03:19:12,743 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2024-07-05 03:19:12,746 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2024-07-05 03:19:12,747 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2024-07-05 03:19:12,748 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2024-07-05 03:19:12,750 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2024-07-05 03:19:12,750 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2024-07-05 03:19:12,751 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2024-07-05 03:19:12,753 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2024-07-05 03:19:12,755 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 12736 bytes
2024-07-05 03:19:12,756 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/obj.pkl (recursive=False)
2024-07-05 03:19:12,757 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/obj.pkl (recursive=False)
2024-07-05 03:19:12,758 - main.py[DEBUG]: [net] init will now be targeting instance id: i-09542aec432627a9a. new=True
2024-07-05 03:19:12,758 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2024-07-05 03:19:12,758 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2024-07-05 03:19:12,758 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:12,786 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2024-07-05 03:19:12,786 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2024-07-05 03:19:12,786 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:12,788 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2024-07-05 03:19:12,788 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2024-07-05 03:19:12,788 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:12,802 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2024-07-05 03:19:12,803 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2024-07-05 03:19:12,804 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:12,812 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2024-07-05 03:19:12,812 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2024-07-05 03:19:12,813 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:12,820 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2024-07-05 03:19:12,820 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:12,820 - util.py[DEBUG]: loaded blob returned None, returning default.
2024-07-05 03:19:12,833 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2024-07-05 03:19:12,833 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2024-07-05 03:19:12,833 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2024-07-05 03:19:12,834 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2024-07-05 03:19:12,834 - util.py[DEBUG]: Reading from /sys/class/net/ens5/name_assign_type (quiet=False)
2024-07-05 03:19:12,834 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/name_assign_type
2024-07-05 03:19:12,834 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2024-07-05 03:19:12,834 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2024-07-05 03:19:12,835 - util.py[DEBUG]: Reading from /sys/class/net/ens5/carrier (quiet=False)
2024-07-05 03:19:12,835 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/carrier
2024-07-05 03:19:12,835 - util.py[DEBUG]: Reading from /sys/class/net/ens5/addr_assign_type (quiet=False)
2024-07-05 03:19:12,835 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/addr_assign_type
2024-07-05 03:19:12,835 - util.py[DEBUG]: Reading from /sys/class/net/ens5/uevent (quiet=False)
2024-07-05 03:19:12,835 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/ens5/uevent
2024-07-05 03:19:12,835 - util.py[DEBUG]: Reading from /sys/class/net/ens5/address (quiet=False)
2024-07-05 03:19:12,835 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens5/address
2024-07-05 03:19:12,835 - __init__.py[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2024-07-05 03:19:12,835 - util.py[DEBUG]: Reading from /sys/class/net/ens5/device/device (quiet=False)
2024-07-05 03:19:12,836 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/ens5/device/device
2024-07-05 03:19:12,836 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2024-07-05 03:19:12,836 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2024-07-05 03:19:12,836 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2024-07-05 03:19:12,836 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2024-07-05 03:19:12,836 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2024-07-05 03:19:12,836 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2024-07-05 03:19:12,836 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2024-07-05 03:19:12,836 - util.py[DEBUG]: Reading from /sys/class/net/ens5/type (quiet=False)
2024-07-05 03:19:12,836 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/ens5/type
2024-07-05 03:19:12,837 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2024-07-05 03:19:12,837 - util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type
2024-07-05 03:19:12,837 - stages.py[DEBUG]: network config disabled by system_cfg
2024-07-05 03:19:12,837 - stages.py[INFO]: network config is disabled by system_cfg
2024-07-05 03:19:12,837 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2024-07-05 03:19:12,837 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2024-07-05 03:19:12,838 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/user-data.txt - wb: [600] 2476 bytes
2024-07-05 03:19:12,839 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/user-data.txt (recursive=False)
2024-07-05 03:19:12,840 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/user-data.txt (recursive=False)
2024-07-05 03:19:12,843 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:12,853 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/user-data.txt.i - wb: [600] 2498 bytes
2024-07-05 03:19:12,854 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/user-data.txt.i (recursive=False)
2024-07-05 03:19:12,855 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/user-data.txt.i (recursive=False)
2024-07-05 03:19:12,855 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/vendor-data.txt - wb: [600] 0 bytes
2024-07-05 03:19:12,856 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/vendor-data.txt (recursive=False)
2024-07-05 03:19:12,858 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/vendor-data.txt (recursive=False)
2024-07-05 03:19:12,859 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/vendor-data.txt.i - wb: [600] 308 bytes
2024-07-05 03:19:12,860 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/vendor-data.txt.i (recursive=False)
2024-07-05 03:19:12,871 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/vendor-data.txt.i (recursive=False)
2024-07-05 03:19:12,872 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/vendor-data2.txt - wb: [600] 0 bytes
2024-07-05 03:19:12,873 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/vendor-data2.txt (recursive=False)
2024-07-05 03:19:12,874 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/vendor-data2.txt (recursive=False)
2024-07-05 03:19:12,876 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/vendor-data2.txt.i - wb: [600] 308 bytes
2024-07-05 03:19:12,877 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/vendor-data2.txt.i (recursive=False)
2024-07-05 03:19:12,878 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/vendor-data2.txt.i (recursive=False)
2024-07-05 03:19:12,879 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-07-05 03:19:12,880 - cc_set_hostname.py[DEBUG]: Setting the hostname to ip-172-31-29-158.us-west-2.compute.internal (ip-172-31-29-158)
2024-07-05 03:19:12,880 - subp.py[DEBUG]: Running command ['hostnamectl', 'set-hostname', 'ip-172-31-29-158.us-west-2.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2024-07-05 03:19:13,090 - __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-172-31-29-158.us-west-2.compute.internal
2024-07-05 03:19:13,090 - subp.py[DEBUG]: Running command ['hostname', 'ip-172-31-29-158.us-west-2.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2024-07-05 03:19:13,117 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmptv0aphqn) - w: [644] 92 bytes/chars
2024-07-05 03:19:13,119 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/sem/consume_data - wb: [644] 25 bytes
2024-07-05 03:19:13,121 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/consume_data (recursive=False)
2024-07-05 03:19:13,124 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/consume_data (recursive=False)
2024-07-05 03:19:13,125 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-09542aec432627a9a/sem/consume_data'>)
2024-07-05 03:19:13,125 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2024-07-05 03:19:13,125 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
2024-07-05 03:19:13,126 - stages.py[DEBUG]: Added default handler for {'text/cloud-config-jsonp', 'text/cloud-config'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2024-07-05 03:19:13,127 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2024-07-05 03:19:13,127 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2024-07-05 03:19:13,127 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2024-07-05 03:19:13,127 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2024-07-05 03:19:13,127 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2024-07-05 03:19:13,127 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2024-07-05 03:19:13,127 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2024-07-05 03:19:13,127 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2024-07-05 03:19:13,127 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2024-07-05 03:19:13,127 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2024-07-05 03:19:13,127 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2024-07-05 03:19:13,127 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2024-07-05 03:19:13,128 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2024-07-05 03:19:13,128 - __init__.py[DEBUG]: {'Content-Type': 'text/cloud-config; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="cloud-config.txt"'}
2024-07-05 03:19:13,128 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, cloud-config.txt, 3) with frequency once-per-instance
2024-07-05 03:19:13,128 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:13,130 - cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
2024-07-05 03:19:13,130 - __init__.py[DEBUG]: {'Content-Type': 'text/x-shellscript; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="user-data.txt"'}
2024-07-05 03:19:13,130 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, user-data.txt, 2) with frequency once-per-instance
2024-07-05 03:19:13,130 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/user-data.txt - wb: [700] 1827 bytes
2024-07-05 03:19:13,141 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/scripts/user-data.txt (recursive=False)
2024-07-05 03:19:13,143 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/scripts/user-data.txt (recursive=False)
2024-07-05 03:19:13,144 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2024-07-05 03:19:13,145 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/cloud-config.txt - wb: [600] 154 bytes
2024-07-05 03:19:13,146 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/cloud-config.txt (recursive=False)
2024-07-05 03:19:13,147 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/cloud-config.txt (recursive=False)
2024-07-05 03:19:13,148 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2024-07-05 03:19:13,148 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2024-07-05 03:19:13,148 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2024-07-05 03:19:13,148 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2024-07-05 03:19:13,148 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2024-07-05 03:19:13,148 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2024-07-05 03:19:13,148 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2024-07-05 03:19:13,148 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2024-07-05 03:19:13,148 - stages.py[DEBUG]: no vendordata from datasource
2024-07-05 03:19:13,148 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2024-07-05 03:19:13,148 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2024-07-05 03:19:13,148 - stages.py[DEBUG]: no vendordata2 from datasource
2024-07-05 03:19:13,148 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2024-07-05 03:19:13,149 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2024-07-05 03:19:13,149 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2024-07-05 03:19:13,149 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:13,179 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2024-07-05 03:19:13,179 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2024-07-05 03:19:13,179 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:13,181 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2024-07-05 03:19:13,181 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2024-07-05 03:19:13,181 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:13,185 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2024-07-05 03:19:13,185 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2024-07-05 03:19:13,185 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:13,202 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2024-07-05 03:19:13,202 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2024-07-05 03:19:13,202 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:13,205 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2024-07-05 03:19:13,205 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:13,205 - util.py[DEBUG]: loaded blob returned None, returning default.
2024-07-05 03:19:13,205 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2024-07-05 03:19:13,205 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2024-07-05 03:19:13,206 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:13,207 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:13,208 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:13,405 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2024-07-05 03:19:13,405 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2024-07-05 03:19:13,405 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2024-07-05 03:19:13,423 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2024-07-05 03:19:13,424 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 16911 bytes
2024-07-05 03:19:13,426 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/obj.pkl (recursive=False)
2024-07-05 03:19:13,427 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/obj.pkl (recursive=False)
2024-07-05 03:19:13,428 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2024-07-05 03:19:13,428 - main.py[DEBUG]: no di_report found in config.
2024-07-05 03:19:13,430 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:13,430 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:13,447 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:13,447 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:13,451 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:13,452 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:13,455 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:13,455 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:13,471 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:13,472 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:13,475 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:13,475 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:13,480 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:13,480 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:13,494 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:13,495 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:13,498 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:13,499 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:13,511 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:13,511 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:13,515 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:13,515 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:13,517 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:13,518 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:13,531 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:13,532 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:13,535 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:13,536 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:13,544 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:13,546 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:13,561 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:13,562 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:13,564 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-07-05 03:19:13,564 - modules.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2024-07-05 03:19:13,565 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2024-07-05 03:19:13,565 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7f7bf78e0dc0>)
2024-07-05 03:19:13,565 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2024-07-05 03:19:13,565 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2024-07-05 03:19:13,565 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2024-07-05 03:19:13,565 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2024-07-05 03:19:13,565 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_seed_random - wb: [644] 25 bytes
2024-07-05 03:19:13,566 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_seed_random (recursive=False)
2024-07-05 03:19:13,567 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_seed_random (recursive=False)
2024-07-05 03:19:13,568 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/i-09542aec432627a9a/sem/config_seed_random'>)
2024-07-05 03:19:13,568 - cc_seed_random.py[DEBUG]: no command provided
2024-07-05 03:19:13,568 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully
2024-07-05 03:19:13,568 - modules.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_bootcmd.py'>) with frequency always
2024-07-05 03:19:13,569 - handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
2024-07-05 03:19:13,569 - helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7f7bf78e0dc0>)
2024-07-05 03:19:13,569 - cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
2024-07-05 03:19:13,569 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
2024-07-05 03:19:13,569 - modules.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance
2024-07-05 03:19:13,569 - handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
2024-07-05 03:19:13,570 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_write_files - wb: [644] 25 bytes
2024-07-05 03:19:13,570 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_write_files (recursive=False)
2024-07-05 03:19:13,572 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_write_files (recursive=False)
2024-07-05 03:19:13,572 - helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-09542aec432627a9a/sem/config_write_files'>)
2024-07-05 03:19:13,572 - cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
2024-07-05 03:19:13,573 - handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
2024-07-05 03:19:13,573 - modules.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_metadata.py'>) with frequency once-per-instance
2024-07-05 03:19:13,573 - handlers.py[DEBUG]: start: init-network/config-write-metadata: running config-write-metadata with frequency once-per-instance
2024-07-05 03:19:13,573 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_write_metadata - wb: [644] 25 bytes
2024-07-05 03:19:13,574 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_write_metadata (recursive=False)
2024-07-05 03:19:13,575 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_write_metadata (recursive=False)
2024-07-05 03:19:13,576 - helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-09542aec432627a9a/sem/config_write_metadata'>)
2024-07-05 03:19:13,576 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsregion - wb: [644] 9 bytes
2024-07-05 03:19:13,584 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2024-07-05 03:19:13,585 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2024-07-05 03:19:13,587 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsregion to 0:0
2024-07-05 03:19:13,587 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsdomain - wb: [644] 13 bytes
2024-07-05 03:19:13,587 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2024-07-05 03:19:13,588 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2024-07-05 03:19:13,589 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsdomain to 0:0
2024-07-05 03:19:13,589 - handlers.py[DEBUG]: finish: init-network/config-write-metadata: SUCCESS: config-write-metadata ran successfully
2024-07-05 03:19:13,589 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2024-07-05 03:19:13,589 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2024-07-05 03:19:13,589 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f7bf78e0fd0>)
2024-07-05 03:19:13,589 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'mode': 'auto', 'devices': ['/'], 'ignore_growroot_disabled': False}
2024-07-05 03:19:13,590 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2024-07-05 03:19:13,635 - util.py[DEBUG]: Reading from /proc/1450/mountinfo (quiet=False)
2024-07-05 03:19:13,636 - util.py[DEBUG]: Read 2941 bytes from /proc/1450/mountinfo
2024-07-05 03:19:13,636 - util.py[DEBUG]: Reading from /sys/class/block/nvme0n1p1/partition (quiet=False)
2024-07-05 03:19:13,636 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/nvme0n1p1/partition
2024-07-05 03:19:13,636 - util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev (quiet=False)
2024-07-05 03:19:13,637 - util.py[DEBUG]: Read 6 bytes from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev
2024-07-05 03:19:13,637 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/nvme0n1', '1'] with allowed return codes [0] (shell=False, capture=True)
2024-07-05 03:19:13,783 - util.py[DEBUG]: resize_devices took 0.148 seconds
2024-07-05 03:19:13,785 - cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/nvme0n1, 1)
2024-07-05 03:19:13,786 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2024-07-05 03:19:13,786 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2024-07-05 03:19:13,786 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2024-07-05 03:19:13,787 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f7bf78e0dc0>)
2024-07-05 03:19:13,787 - util.py[DEBUG]: Reading from /proc/1450/mountinfo (quiet=False)
2024-07-05 03:19:13,787 - util.py[DEBUG]: Read 2941 bytes from /proc/1450/mountinfo
2024-07-05 03:19:13,788 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/nvme0n1p1 mnt_point=/ path=/
2024-07-05 03:19:13,788 - cc_resizefs.py[DEBUG]: Resizing / (xfs) using xfs_growfs /
2024-07-05 03:19:13,789 - util.py[DEBUG]: Forked child 1583 who will run callback log_time
2024-07-05 03:19:13,790 - cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=xfs, val=noblock)
2024-07-05 03:19:13,790 - subp.py[DEBUG]: Running command ('xfs_growfs', '/') with allowed return codes [0] (shell=False, capture=True)
2024-07-05 03:19:13,790 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2024-07-05 03:19:13,790 - modules.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disk_setup.py'>) with frequency once-per-instance
2024-07-05 03:19:13,802 - handlers.py[DEBUG]: start: init-network/config-disk_setup: running config-disk_setup with frequency once-per-instance
2024-07-05 03:19:13,802 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_disk_setup - wb: [644] 25 bytes
2024-07-05 03:19:13,805 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_disk_setup (recursive=False)
2024-07-05 03:19:13,807 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_disk_setup (recursive=False)
2024-07-05 03:19:13,807 - helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-09542aec432627a9a/sem/config_disk_setup'>)
2024-07-05 03:19:13,808 - handlers.py[DEBUG]: finish: init-network/config-disk_setup: SUCCESS: config-disk_setup ran successfully
2024-07-05 03:19:13,808 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2024-07-05 03:19:13,808 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2024-07-05 03:19:13,809 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_mounts - wb: [644] 24 bytes
2024-07-05 03:19:13,810 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_mounts (recursive=False)
2024-07-05 03:19:13,821 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_mounts (recursive=False)
2024-07-05 03:19:13,822 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-09542aec432627a9a/sem/config_mounts'>)
2024-07-05 03:19:13,823 - cc_mounts.py[DEBUG]: mounts configuration is []
2024-07-05 03:19:13,823 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2024-07-05 03:19:13,823 - util.py[DEBUG]: Read 217 bytes from /etc/fstab
2024-07-05 03:19:13,823 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2024-07-05 03:19:13,823 - DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
2024-07-05 03:19:13,823 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
2024-07-05 03:19:13,823 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2024-07-05 03:19:13,824 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2024-07-05 03:19:13,824 - DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
2024-07-05 03:19:13,824 - cc_mounts.py[DEBUG]: changed default device swap => None
2024-07-05 03:19:13,824 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2024-07-05 03:19:13,824 - cc_mounts.py[DEBUG]: no need to setup swap
2024-07-05 03:19:13,824 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2024-07-05 03:19:13,824 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully
2024-07-05 03:19:13,824 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_hostname.py'>) with frequency always
2024-07-05 03:19:13,824 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency always
2024-07-05 03:19:13,824 - helpers.py[DEBUG]: Running config-set_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f7bf78e7190>)
2024-07-05 03:19:13,825 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2024-07-05 03:19:13,825 - util.py[DEBUG]: Read 92 bytes from /var/lib/cloud/data/set-hostname
2024-07-05 03:19:13,825 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2024-07-05 03:19:13,825 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully
2024-07-05 03:19:13,825 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2024-07-05 03:19:13,825 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2024-07-05 03:19:13,825 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f7bf78e0dc0>)
2024-07-05 03:19:13,826 - cc_update_hostname.py[DEBUG]: Updating hostname to ip-172-31-29-158.us-west-2.compute.internal (ip-172-31-29-158)
2024-07-05 03:19:13,826 - subp.py[DEBUG]: Running command ['hostname'] with allowed return codes [0] (shell=False, capture=True)
2024-07-05 03:19:13,831 - __init__.py[DEBUG]: Attempting to update hostname to ip-172-31-29-158.us-west-2.compute.internal in 1 files
2024-07-05 03:19:13,832 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 43 bytes
2024-07-05 03:19:13,833 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2024-07-05 03:19:13,835 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2024-07-05 03:19:13,836 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2024-07-05 03:19:13,836 - modules.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always
2024-07-05 03:19:13,836 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with frequency always
2024-07-05 03:19:13,836 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0x7f7bf78e0c40>)
2024-07-05 03:19:13,836 - cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update_etc_hosts
2024-07-05 03:19:13,836 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully
2024-07-05 03:19:13,836 - modules.py[DEBUG]: Running module ca-certs (<module 'cloudinit.config.cc_ca_certs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ca_certs.py'>) with frequency once-per-instance
2024-07-05 03:19:13,837 - handlers.py[DEBUG]: start: init-network/config-ca-certs: running config-ca-certs with frequency once-per-instance
2024-07-05 03:19:13,837 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_ca_certs - wb: [644] 25 bytes
2024-07-05 03:19:13,838 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_ca_certs (recursive=False)
2024-07-05 03:19:13,839 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_ca_certs (recursive=False)
2024-07-05 03:19:13,839 - helpers.py[DEBUG]: Running config-ca-certs using lock (<FileLock using file '/var/lib/cloud/instances/i-09542aec432627a9a/sem/config_ca_certs'>)
2024-07-05 03:19:13,839 - cc_ca_certs.py[DEBUG]: Skipping module named ca-certs, no 'ca_certs' key in configuration
2024-07-05 03:19:13,839 - handlers.py[DEBUG]: finish: init-network/config-ca-certs: SUCCESS: config-ca-certs ran successfully
2024-07-05 03:19:13,839 - modules.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_rsyslog.py'>) with frequency once-per-instance
2024-07-05 03:19:13,840 - handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
2024-07-05 03:19:13,840 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_rsyslog - wb: [644] 25 bytes
2024-07-05 03:19:13,861 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_rsyslog (recursive=False)
2024-07-05 03:19:13,863 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_rsyslog (recursive=False)
2024-07-05 03:19:13,863 - helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-09542aec432627a9a/sem/config_rsyslog'>)
2024-07-05 03:19:13,863 - cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
2024-07-05 03:19:13,863 - handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
2024-07-05 03:19:13,863 - modules.py[DEBUG]: Running module selinux (<module 'cloudinit.config.cc_selinux' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_selinux.py'>) with frequency once-per-instance
2024-07-05 03:19:13,864 - handlers.py[DEBUG]: start: init-network/config-selinux: running config-selinux with frequency once-per-instance
2024-07-05 03:19:13,864 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_selinux - wb: [644] 25 bytes
2024-07-05 03:19:13,865 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_selinux (recursive=False)
2024-07-05 03:19:13,866 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_selinux (recursive=False)
2024-07-05 03:19:13,866 - helpers.py[DEBUG]: Running config-selinux using lock (<FileLock using file '/var/lib/cloud/instances/i-09542aec432627a9a/sem/config_selinux'>)
2024-07-05 03:19:13,879 - util.py[DEBUG]: backgrounded Resizing took 0.089 seconds
2024-07-05 03:19:13,887 - cc_selinux.py[DEBUG]: Current SELinux state is enabled
2024-07-05 03:19:13,887 - cc_selinux.py[DEBUG]: Current SELinux mode is permissive
2024-07-05 03:19:13,887 - cc_selinux.py[DEBUG]: Configured SELinux mode is permissive
2024-07-05 03:19:13,887 - cc_selinux.py[DEBUG]: Current SELinux policy is targeted
2024-07-05 03:19:13,887 - cc_selinux.py[DEBUG]: No SELinux configuration, skipping
2024-07-05 03:19:13,888 - handlers.py[DEBUG]: finish: init-network/config-selinux: SUCCESS: config-selinux ran successfully
2024-07-05 03:19:13,888 - modules.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2024-07-05 03:19:13,888 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2024-07-05 03:19:13,889 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_users_groups - wb: [644] 25 bytes
2024-07-05 03:19:13,890 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_users_groups (recursive=False)
2024-07-05 03:19:13,892 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_users_groups (recursive=False)
2024-07-05 03:19:13,892 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-09542aec432627a9a/sem/config_users_groups'>)
2024-07-05 03:19:13,893 - __init__.py[INFO]: User ec2-user already exists, skipping.
2024-07-05 03:19:13,893 - subp.py[DEBUG]: Running command ['passwd', '-l', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
2024-07-05 03:19:13,984 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2024-07-05 03:19:13,998 - util.py[DEBUG]: Read 4375 bytes from /etc/sudoers
2024-07-05 03:19:14,000 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d (recursive=False)
2024-07-05 03:19:14,001 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - ab: [None] 59 bytes
2024-07-05 03:19:14,002 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d/90-cloud-init-users (recursive=False)
2024-07-05 03:19:14,004 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2024-07-05 03:19:14,004 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2024-07-05 03:19:14,005 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2024-07-05 03:19:14,006 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_ssh - wb: [644] 25 bytes
2024-07-05 03:19:14,008 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_ssh (recursive=False)
2024-07-05 03:19:14,009 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_ssh (recursive=False)
2024-07-05 03:19:14,010 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-09542aec432627a9a/sem/config_ssh'>)
2024-07-05 03:19:14,011 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2024-07-05 03:19:14,054 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2024-07-05 03:19:14,072 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2024-07-05 03:19:14,095 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2024-07-05 03:19:14,117 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2024-07-05 03:19:14,117 - util.py[DEBUG]: Read 130 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2024-07-05 03:19:14,117 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2024-07-05 03:19:14,117 - util.py[DEBUG]: Read 210 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2024-07-05 03:19:14,118 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2024-07-05 03:19:14,131 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2024-07-05 03:19:14,132 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 1000:1000
2024-07-05 03:19:14,134 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=False)
2024-07-05 03:19:14,135 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2024-07-05 03:19:14,136 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-07-05 03:19:14,136 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-07-05 03:19:14,137 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 1000:1000
2024-07-05 03:19:14,137 - util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
2024-07-05 03:19:14,137 - util.py[DEBUG]: Read 0 bytes from /home/ec2-user/.ssh/authorized_keys
2024-07-05 03:19:14,137 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 88 bytes
2024-07-05 03:19:14,138 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-07-05 03:19:14,138 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-07-05 03:19:14,139 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=True)
2024-07-05 03:19:14,141 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2024-07-05 03:19:14,142 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2024-07-05 03:19:14,143 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2024-07-05 03:19:14,145 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2024-07-05 03:19:14,146 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-07-05 03:19:14,146 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-07-05 03:19:14,146 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2024-07-05 03:19:14,146 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2024-07-05 03:19:14,146 - util.py[DEBUG]: Read 0 bytes from /root/.ssh/authorized_keys
2024-07-05 03:19:14,147 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 254 bytes
2024-07-05 03:19:14,147 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-07-05 03:19:14,147 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-07-05 03:19:14,147 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2024-07-05 03:19:14,149 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2024-07-05 03:19:14,150 - main.py[DEBUG]: Ran 17 modules with 0 failures
2024-07-05 03:19:14,150 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpwwp1mldn) - w: [644] 486 bytes/chars
2024-07-05 03:19:14,151 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-07-05 03:19:14,151 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2024-07-05 03:19:14,151 - util.py[DEBUG]: cloud-init mode 'init' took 2.608 seconds (2.60)
2024-07-05 03:19:14,161 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2024-07-05 03:19:15,386 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:config' at Fri, 05 Jul 2024 03:19:15 +0000. Up 11.85 seconds.
2024-07-05 03:19:15,392 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:15,392 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:15,411 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:15,411 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:15,415 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:15,415 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:15,421 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:15,421 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:15,432 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:15,432 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:15,436 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:15,436 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:15,452 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:15,452 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:15,457 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:15,457 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:15,460 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:15,460 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:15,471 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:15,471 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:15,474 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-07-05 03:19:15,474 - modules.py[INFO]: Skipping modules 'ssh-import-id' because they are not verified on distro 'amazon'.  To run anyway, add them to 'unverified_modules' in config.
2024-07-05 03:19:15,475 - modules.py[DEBUG]: Running module keyboard (<module 'cloudinit.config.cc_keyboard' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_keyboard.py'>) with frequency once-per-instance
2024-07-05 03:19:15,475 - handlers.py[DEBUG]: start: modules-config/config-keyboard: running config-keyboard with frequency once-per-instance
2024-07-05 03:19:15,475 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_keyboard - wb: [644] 25 bytes
2024-07-05 03:19:15,478 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_keyboard (recursive=False)
2024-07-05 03:19:15,481 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_keyboard (recursive=False)
2024-07-05 03:19:15,482 - helpers.py[DEBUG]: Running config-keyboard using lock (<FileLock using file '/var/lib/cloud/instances/i-09542aec432627a9a/sem/config_keyboard'>)
2024-07-05 03:19:15,482 - cc_keyboard.py[DEBUG]: Skipping module named keyboard, no 'keyboard' section found
2024-07-05 03:19:15,483 - handlers.py[DEBUG]: finish: modules-config/config-keyboard: SUCCESS: config-keyboard ran successfully
2024-07-05 03:19:15,483 - modules.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2024-07-05 03:19:15,483 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2024-07-05 03:19:15,483 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_locale - wb: [644] 25 bytes
2024-07-05 03:19:15,492 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_locale (recursive=False)
2024-07-05 03:19:15,494 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_locale (recursive=False)
2024-07-05 03:19:15,494 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-09542aec432627a9a/sem/config_locale'>)
2024-07-05 03:19:15,495 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2024-07-05 03:19:15,495 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2024-07-05 03:19:15,495 - cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
2024-07-05 03:19:15,495 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2024-07-05 03:19:15,495 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2024-07-05 03:19:15,495 - util.py[DEBUG]: Writing to /etc/locale.conf - wb: [644] 17 bytes
2024-07-05 03:19:15,498 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2024-07-05 03:19:15,502 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2024-07-05 03:19:15,502 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
2024-07-05 03:19:15,502 - modules.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2024-07-05 03:19:15,502 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2024-07-05 03:19:15,503 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_set_passwords - wb: [644] 25 bytes
2024-07-05 03:19:15,512 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_set_passwords (recursive=False)
2024-07-05 03:19:15,513 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_set_passwords (recursive=False)
2024-07-05 03:19:15,513 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-09542aec432627a9a/sem/config_set_passwords'>)
2024-07-05 03:19:15,514 - subp.py[DEBUG]: Running command ['systemctl', 'status', 'sshd'] with allowed return codes [0] (shell=False, capture=True)
2024-07-05 03:19:15,542 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2024-07-05 03:19:15,542 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2024-07-05 03:19:15,543 - ssh_util.py[DEBUG]: line 65: option PasswordAuthentication already set to no
2024-07-05 03:19:15,543 - cc_set_passwords.py[DEBUG]: No need to restart SSH service, PasswordAuthentication not updated.
2024-07-05 03:19:15,543 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2024-07-05 03:19:15,543 - modules.py[DEBUG]: Running module yum-variables (<module 'cloudinit.config.cc_yum_variables' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_variables.py'>) with frequency once-per-instance
2024-07-05 03:19:15,544 - handlers.py[DEBUG]: start: modules-config/config-yum-variables: running config-yum-variables with frequency once-per-instance
2024-07-05 03:19:15,544 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_yum_variables - wb: [644] 25 bytes
2024-07-05 03:19:15,545 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_yum_variables (recursive=False)
2024-07-05 03:19:15,547 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_yum_variables (recursive=False)
2024-07-05 03:19:15,547 - helpers.py[DEBUG]: Running config-yum-variables using lock (<FileLock using file '/var/lib/cloud/instances/i-09542aec432627a9a/sem/config_yum_variables'>)
2024-07-05 03:19:15,547 - cc_yum_variables.py[INFO]: handling yum-variables
2024-07-05 03:19:15,547 - cc_yum_variables.py[INFO]: cfg = {'cloud_final_modules': [['scripts-user', 'always']], 'repo_releasever': 2023.5, 'repo_upgrade': 'none', 'power_state': {'delay': 'now', 'mode': 'reboot', 'message': 'Rebooting machine to apply SELinux kernel commandline setting', 'condition': 'test -f /run/cloud-init-selinux-reboot'}, 'write_metadata': [{'path': '/etc/dnf/vars/awsregion', 'data': [{'identity': 'region'}, 'default']}, {'path': '/etc/dnf/vars/awsdomain', 'data': [{'metadata': 'services/domain'}, 'amazonaws.com']}], '_log': ['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n", '[handler_cloudLogHandler]\nclass=handlers.SysLogHandler\nlevel=DEBUG\nformatter=simpleFormatter\nargs=("/dev/log", handlers.SysLogHandler.LOG_USER)\n'], 'log_cfgs': [['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n"]], 'output': {'all': '| tee -a /var/log/cloud-init-output.log'}, 'network': {'config': 'disabled'}, 'datasource_list': ['Ec2', 'None'], 'datasource': {'Ec2': {'metadata_urls': ['http://169.254.169.254:80', 'http://[fd00:ec2::254]:80'], 'apply_full_imds_network_config': False}}, 'ssh_genkeytypes': ['ed25519', 'ecdsa'], 'users': ['default'], 'disable_root': True, 'mount_default_fields': [None, None, 'auto', 'defaults,nofail', '0', '2'], 'resize_rootfs': 'noblock', 'resize_rootfs_tmp': '/dev', 'ssh_pwauth': False, 'preserve_hostname': False, 'cloud_init_modules': ['migrator', 'seed_random', 'bootcmd', 'write-files', 'write-metadata', 'growpart', 'resizefs', 'disk_setup', 'mounts', 'set_hostname', 'update_hostname', 'update_etc_hosts', 'ca-certs', 'rsyslog', 'selinux', 'users-groups', 'ssh'], 'cloud_config_modules': ['ssh-import-id', 'keyboard', 'locale', 'set-passwords', 'yum-variables', 'yum-add-repo', 'ntp', 'timezone', 'disable-ec2-metadata', 'runcmd'], 'def_log_file': '/var/log/cloud-init.log', 'syslog_fix_perms': ['syslog:adm', 'root:adm', 'root:wheel', 'root:root'], 'vendor_data': {'enabled': True, 'prefix': []}, 'vendor_data2': {'enabled': True, 'prefix': []}}
2024-07-05 03:19:15,547 - cc_yum_variables.py[INFO]: No yum vars to delete
2024-07-05 03:19:15,547 - cc_yum_variables.py[INFO]: No yum vars to set
2024-07-05 03:19:15,548 - handlers.py[DEBUG]: finish: modules-config/config-yum-variables: SUCCESS: config-yum-variables ran successfully
2024-07-05 03:19:15,548 - modules.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_add_repo.py'>) with frequency once-per-instance
2024-07-05 03:19:15,548 - handlers.py[DEBUG]: start: modules-config/config-yum-add-repo: running config-yum-add-repo with frequency once-per-instance
2024-07-05 03:19:15,548 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_yum_add_repo - wb: [644] 25 bytes
2024-07-05 03:19:15,561 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_yum_add_repo (recursive=False)
2024-07-05 03:19:15,563 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_yum_add_repo (recursive=False)
2024-07-05 03:19:15,563 - helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-09542aec432627a9a/sem/config_yum_add_repo'>)
2024-07-05 03:19:15,563 - cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
2024-07-05 03:19:15,564 - handlers.py[DEBUG]: finish: modules-config/config-yum-add-repo: SUCCESS: config-yum-add-repo ran successfully
2024-07-05 03:19:15,564 - modules.py[DEBUG]: Running module ntp (<module 'cloudinit.config.cc_ntp' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ntp.py'>) with frequency once-per-instance
2024-07-05 03:19:15,564 - handlers.py[DEBUG]: start: modules-config/config-ntp: running config-ntp with frequency once-per-instance
2024-07-05 03:19:15,564 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_ntp - wb: [644] 24 bytes
2024-07-05 03:19:15,565 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_ntp (recursive=False)
2024-07-05 03:19:15,567 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_ntp (recursive=False)
2024-07-05 03:19:15,567 - helpers.py[DEBUG]: Running config-ntp using lock (<FileLock using file '/var/lib/cloud/instances/i-09542aec432627a9a/sem/config_ntp'>)
2024-07-05 03:19:15,567 - cc_ntp.py[DEBUG]: Skipping module named ntp, not present or disabled by cfg
2024-07-05 03:19:15,567 - handlers.py[DEBUG]: finish: modules-config/config-ntp: SUCCESS: config-ntp ran successfully
2024-07-05 03:19:15,568 - modules.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_timezone.py'>) with frequency once-per-instance
2024-07-05 03:19:15,568 - handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
2024-07-05 03:19:15,568 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_timezone - wb: [644] 24 bytes
2024-07-05 03:19:15,569 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_timezone (recursive=False)
2024-07-05 03:19:15,570 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_timezone (recursive=False)
2024-07-05 03:19:15,570 - helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-09542aec432627a9a/sem/config_timezone'>)
2024-07-05 03:19:15,570 - cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
2024-07-05 03:19:15,570 - handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
2024-07-05 03:19:15,571 - modules.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disable_ec2_metadata.py'>) with frequency always
2024-07-05 03:19:15,580 - handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
2024-07-05 03:19:15,580 - helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7effc1d1fcd0>)
2024-07-05 03:19:15,580 - cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
2024-07-05 03:19:15,581 - handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
2024-07-05 03:19:15,581 - modules.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_runcmd.py'>) with frequency once-per-instance
2024-07-05 03:19:15,581 - handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
2024-07-05 03:19:15,581 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_runcmd - wb: [644] 25 bytes
2024-07-05 03:19:15,582 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_runcmd (recursive=False)
2024-07-05 03:19:15,583 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-09542aec432627a9a/sem/config_runcmd (recursive=False)
2024-07-05 03:19:15,584 - helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-09542aec432627a9a/sem/config_runcmd'>)
2024-07-05 03:19:15,584 - cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
2024-07-05 03:19:15,584 - handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
2024-07-05 03:19:15,584 - main.py[DEBUG]: Ran 9 modules with 0 failures
2024-07-05 03:19:15,585 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpvkh43g2d) - w: [644] 514 bytes/chars
2024-07-05 03:19:15,585 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-07-05 03:19:15,585 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2024-07-05 03:19:15,585 - util.py[DEBUG]: cloud-init mode 'modules' took 0.428 seconds (0.43)
2024-07-05 03:19:15,586 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2024-07-05 03:19:16,461 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:final' at Fri, 05 Jul 2024 03:19:16 +0000. Up 12.94 seconds.
2024-07-05 03:19:16,472 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-07-05 03:19:16,472 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-07-05 03:19:16,475 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-07-05 03:19:16,476 - modules.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_scripts_user.py'>) with frequency always
2024-07-05 03:19:16,476 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency always
2024-07-05 03:19:16,476 - helpers.py[DEBUG]: Running config-scripts-user using lock (<cloudinit.helpers.DummyLock object at 0x7f7f62d06f10>)
2024-07-05 03:19:16,476 - subp.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/user-data.txt'] with allowed return codes [0] (shell=False, capture=False)
2024-07-05 03:19:27,578 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
2024-07-05 03:19:27,579 - main.py[DEBUG]: Ran 1 modules with 0 failures
2024-07-05 03:19:27,579 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmph1tbznnw) - w: [644] 542 bytes/chars
2024-07-05 03:19:27,580 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmp185dro6g) - w: [644] 64 bytes/chars
2024-07-05 03:19:27,580 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2024-07-05 03:19:27,580 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-07-05 03:19:27,580 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2024-07-05 03:19:27,580 - util.py[DEBUG]: cloud-init mode 'modules' took 11.320 seconds (9.86)
2024-07-05 03:19:27,581 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
